/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzleia;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.LinkedList;
import java.util.Scanner;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;
import GeneracionYPrueba.GeneracionYPrueba;

/**
 *
 * @author erick
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        botonArchivo = new javax.swing.JButton();
        labelfichero = new javax.swing.JLabel();
        tabPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setText("Método");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 90, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Búsqueda por anchura", "Búsqueda por profundidad", "Búsqueda límitada por profundidad", "Búsqueda por profundidad iterativa", "Búsqueda bidireccional", "Generación y prueba", "Métodos de escalada", "Búsqueda del primero mejor", "Algoritmo A*", "Minimo Máximo", " " }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(100, 10, 270, 24);

        jLabel2.setText("Fichero");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 50, 80, 20);

        botonArchivo.setText("Abrir");
        botonArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(botonArchivo);
        botonArchivo.setBounds(420, 10, 150, 25);

        labelfichero.setText("No se ha seleccionado fichero");
        jPanel1.add(labelfichero);
        labelfichero.setBounds(100, 50, 300, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 660, 100);
        getContentPane().add(tabPanel);
        tabPanel.setBounds(10, 130, 660, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonArchivoActionPerformed

    public void SeleccionarArchivo() throws FileNotFoundException
    {
        String path = "/home/erick/Escritorio/1S2020/IAYIS/Practica/PuzzleIA/ficheros/puzzle1.txt"; 
        Tablero tablero1 = new Tablero(obtenerMatriz(path));
        GeneracionYPrueba met1 = new GeneracionYPrueba(tablero1);
        met1.Run();                    
    }
    
    public int[][] obtenerMatriz(String path) throws FileNotFoundException
    {   
        int data[][] = null ;
        File archivo= new File(path);    
        Scanner sc = new Scanner(archivo); 
        /*Obtenemos cada una de las lineas*/
        LinkedList<String> lineas = new LinkedList<String>();
        while (sc.hasNextLine())
        {
            lineas.add(sc.nextLine());            
        }                
        /*Verificamos que la matriz sea cuadrada*/        
        
        /*reservamos espacio para la nueva matriz*/
        data = new int[lineas.size()][lineas.size()];
        /*Obtenemos los datos de cada fila que está en la columna*/
        int y = 0;
        StringTokenizer celdas = null;
        for(int i = 0; i< lineas.size(); i++)
        {
            String lineaActual = lineas.get(i);            
            y =0 ; 
           celdas =  new StringTokenizer (lineaActual,",");
            while(celdas.hasMoreTokens())
            {
               data[i][y] = Integer.parseInt(celdas.nextToken());                
               y++;
            }            
        }
        return data;
    } 
    
    public void abrirArchivo()
    {
        JFileChooser seleccionadorArchivo = new JFileChooser();
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonArchivo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelfichero;
    private javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables
}
